pacstrap: initialize the keyring in the new root if copykeyring=0
archlinux/arch-install-scripts pull request #23
Opened 2022-08-19 18:19 UTC by YHNdnzj

As I explained in [archiso#190](https://gitlab.archlinux.org/archlinux/archiso/-/issues/190), the keyring on the host might have be initialized before the currect system time is set, resulting in future issues. As [FS#62826](https://bugs.archlinux.org/task/62826) has been fixed, `archlinux-keyring` can now populate itself during installation. So, when `-G` is specified, instead of doing nothing, we can initialize an empty keyring and let pacman do the populating.

Also, I'm hoping that we can make this default in the future, which would fix the archiso issue without "automating and pre-configuring even more things" on their side :)

2022-08-23 17:31 UTC, nl6720 requested changes
I don't think it's a good idea to suddenly change existing behavior. This will affect cases where you **do not** want the pacman keyring initialized. E.g. [`mkarchiso`](https://gitlab.archlinux.org/archlinux/archiso/-/blob/master/archiso/mkarchiso) uses the `-G` option.

IMHO it would be better to add a new command line flag for this feature.

2022-08-23 18:22 UTC, YHNdnzj commented
@nl6720 Updated to use `-K` instead (implies `-G`).

2022-08-25 07:08 UTC, nl6720 approved these changes
LGTM.

Ideally the new option should be added to bash and zsh completions, but it's not the only one that's missing.

2022-08-25 14:57 UTC, nl6720 commented
As a zsh user... :frowning_face:

2022-08-28 12:57 UTC, merged

2022-08-28 12:58 UTC, Foxboron commented
Thanks!